spring.application.name=investx-backend

server.port=8080

spring.data.mongodb.uri=mongodb://localhost:27017/investx
spring.data.mongodb.database=investx

# JWT
jwt.secret=InvestXSuperSecretKeyForJWTAuthentication2026VeryLongKey
jwt.expiration=86400000